name: Update-Image
on:
  repository_dispatch:
    types:
      - custom-event
    inputs:
      image:
        description: "image for production"
        required: true
        default: "latest"
# on:
#   workflow_dispatch:
#     inputs:
#       image:
#         description: "image for production"
#         required: true
#         default: "latest"
jobs:
  update-image:
    runs-on: ubuntu-24.04
    steps:
      - name: Print inputs image
        run: echo  image is ${{ inputs.image }}

      - name: export image to IMAGE
        run: export TAG_IMAGE=${{ inputs.image }}

      - name: print $TAG_IMAGE
        run: echo $TAG_IMAGE

      - name: Checkout
        uses: actions/checkout@v4

      # - name: edit file with image
      #   run: bash ./.bash/automate.bash

      - name: yq update image file
        run: yq -i '.spec.template.spec.containers[0].image = "flhpktech/rust-demo:${{ inputs.image }}"' ./deployments/rust-demo.yaml

      - name: Update Reprository
        working-directory: .
        run: |-
          git config --global user.email "flamezaxaou1@@gmail.com"
          git config --global user.name "hashtagf"
          git add .
          git commit -am "edit image version to ${{ inputs.image }}"
          git push origin main
