name: Update-Image
on:
  workflow_dispatch:
    inputs:
      image:
        description: "image for production"
        required: true
        default: "latest"
jobs:
  update-image:
    runs-on: ubuntu-24.04
    steps:
      - name: Print inputs image
        run: echo  image is ${{ inputs.image }}

      - name: export image to IMAGE
        run: export TAG_IMAGE=${{ inputs.image }}
      - name: Checkout
        uses: actions/checkout@v4

      - name: edit file with image
        run: bash ./.bash/automate.bash

      - name: Update Reprository
        working-directory: k8s-workshop
        run: |-
          git config --global user.email "flamezaxaou1@@gmail.com"
          git config --global user.name "hashtagf"
          git add .
          git commit -am "edit image version to ${{ inputs.image }}"
          git push origin main
