name: Update-Image
on:
  workflow_dispatch:
    inputs:
      image:
        description: "image for production"
        required: true
        default: "latest"
jobs:
  update-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
