name: Update-Image
on:
  repository_dispatch:
    types:
      - update-image-event
# on:
#   workflow_dispatch:
#     inputs:
#       image:
#         description: "image for production"
#         required: true
#         default: "latest"
jobs:
  update-image:
    runs-on: ubuntu-24.04
    steps:
      - name: Print inputs image
        # run: echo  image is ${{ inputs.image }}
        run: echo  image is ${{ github.event.client_payload.tag_image }}

      - name: Checkout
        uses: actions/checkout@v4

      # - name: edit file with image
      #   run: bash ./.bash/automate.bash

      - name: yq update image file
        run: yq -i '.spec.template.spec.containers[0].image = "flhpktech/rust-demo:${{ github.event.client_payload.tag_image }}"' ./deployments/rust-demo.yaml

      - name: Update Reprository
        working-directory: .
        run: |-
          git config --global user.email "flamezaxaou1@@gmail.com"
          git config --global user.name "hashtagf"
          git add .
          git commit -am "edit image version to ${{ github.event.client_payload.tag_image }}"
          git push origin main
